# unicomm medua server egress
# support@unicomm.pro
version: "3"
services:
  uc.media.score:
    image: cr.yandex/crpi5ll6mqcn793fvu9i/unicchat.solid/prod:prod250211
    container_name: uc.score
    restart: unless-stopped
    network_mode: "host"
    environment:
      - UniComm.Config=/app/sc.config.json
    volumes:
      - ./config/sc.config.json:/app/sc.config.json

