version: "3"
services:
  unic.chat.free:
    container_name: unic.chat.appserver
    image: cr.yandex/crpvpl7g37r2id3i2qe5/unic_chat_appserver:prod.6-2.1.69
    restart: on-failure
    env_file:
      - ./common_env.env
      - ./appserver_env.env
    volumes:
      - chat_data:/app/uploads
    ports:
      - "8080:3000"
    networks:
      - unicchat-frontend

networks:
  unicchat-frontend:
    driver: bridge
    external: true
volumes:
  chat_data:
    driver: local
