version: '3.7'
services:
  solid:
    image: cr.yandex/yc/unicchat/solid:${SOLID_IMAGE_VERSION}
    container_name: unic.chat.solid
    environment:
      - UnInit.0=${UnInit.0}
      - UnInit.1=${UnInit.1}
      - InitConfig:Names=${InitConfig:Names}
      - Plugins:Attach=${Plugins:Attach}
      - UnicLicense=${UnicLicense}
    networks:
      - unicchat-backend
      - unicchat-frontend
    ports:
      - "8881:8881"
networks:
  unicchat-backend:
    external: true
  unicchat-frontend:
    external: true
