version: "3"
services:
  unic.chat.free:
    container_name: unic.chat.appserver
    image: cr.yandex/crpvpl7g37r2id3i2qe5/unic_chat_appserver:prod.6-2.1.59
    restart: on-failure
    environment:
      - MONGO_URL=mongodb://username:password@mongodb:27017/?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://username:password@mongodb:27017/local
      - ROOT_URL=http://localhost:3000
      # ваш адрес solid
      - UNIC_SOLID_HOST=http://адрес_solid:8081
      - PORT=3000
      - DEPLOY_METHOD=docker
      # dns onlyoffice
      - ONLYOFFICE_HOST=https://dns_name_onlyoffice
      - LIVEKIT_HOST=wss://lk-yc.unic.chat
    volumes:
      - chat_data:/app/uploads
     # свой порт на котором будет доступен сервер UnicChat
    ports:
      - "8080:3000"
    networks:
      - unicchat-frontend

networks:
  unicchat-frontend:
    driver: bridge
    external: true
