version: "3"
services:
  unic.chat.free:
    container_name: unic.chat.appserver.free
    image: cr.yandex/crpvpl7g37r2id3i2qe5/unic_chat_appserver:prod.6-2.1.35
    restart: on-failure
    environment:
      - MONGO_URL=mongodb://ucusername:ucpassword@mongodb:27017/db_name?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://ucusername:ucpassword@mongodb:27017/local
      - ROOT_URL=http://localhost:8080
      - PORT=8080
      - DEPLOY_METHOD=docker
      - LIVEKIT_HOST=wss://lk-yc.unic.chat # ВКС по умолчанию развернут и поддерживается компанией Uniccom. При необходимости, возможно настроить и использовать собственное решение.

    ports:
      # указать свой порт на котором будет доступен сервер UnicChat
      - "8080:8080"
    networks:
      - unic-chat-free

networks:
  unic-chat-free:
    driver: bridge
