version: '3.7'
services:
  appserver:
    image: cr.yandex/yc/unicchat/appserver:${APPSERVER_IMAGE_VERSION}
    container_name: unic.chat.appserver
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_OPLOG_URL=${MONGO_OPLOG_URL}
      - ROOT_URL=${ROOT_URL}
      - UNIC_SOLID_HOST=${UNIC_SOLID_HOST}
      - PORT=${PORT}
      - DEPLOY_METHOD=${DEPLOY_METHOD}
      - ONLYOFFICE_HOST=${ONLYOFFICE_HOST}
      - LIVEKIT_HOST=${LIVEKIT_HOST}
      - InitConfig:Names=${InitConfig:Names}
      - Plugins:Attach=${Plugins:Attach}
      - UnicLicense=${UnicLicense}
    networks:
      - unicchat-backend
      - unicchat-frontend
    ports:
      - "8080:3000"
networks:
  unicchat-backend:
    external: true
  unicchat-frontend:
    external: true
