logging:
  logs:
    default:
      level: INFO
storage:
  "module": "file_system"
  "root": "/data"
apps:
  tls:
    certificates:
      automate:
        - media-server.your_domain
        - turn.media-server.your_domain
        - whip.media-server.your_domain
  layer4:
    servers:
      main:
        listen: [":443"]
        routes:
          - match:
              - tls:
                  sni:
                    - "turn.media-server.your_domain"
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["media-server.your_domain:5349"]
          - match:
              - tls:
                  sni:
                    - "media-server.your_domain"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["media-server.your_domain:7880"]
          - match:
              - tls:
                  sni:
                    - "whip.media-server.your_domain"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["media-server.your_domain:8080"]
