log_level: info
port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  enable_loopback_candidate: false
redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
turn:
  enabled: true
  domain: turn.media-server.your_domain
  tls_port: 5349
  udp_port: 3478
  external_tls: true
keys:
  gs528shsa3gGFFD: jshGshsil2439dxznHGSOPWIjnxb27e02nzak238iHSHw32i9o
