version: "3"
services:
  mongodb:
    image: docker.io/bitnamilegacy/mongodb:${MONGODB_VERSION:-4.4}
    container_name: unic.chat.db.mongo
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    networks:
      - unicchat-backend
      - unicchat-frontend

networks:
  unicchat-frontend:
    driver: bridge
    external: true
  unicchat-backend:
    driver: bridge
    external: true

volumes:
  mongodb_data:
    driver: local

