version: "3"
services:
  mongodb:
    image: cr.yandex/crps5m51hmah43pmfb23/mongodb:4.4
    container_name: unic.chat.db.mongo
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    networks:
      - unicchat-backend
      - unicchat-frontend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  unicchat-frontend:
    driver: bridge
    external: true
  unicchat-backend:
    driver: bridge
    external: true

volumes:
  mongodb_data:
    driver: local



