version: "3.8"
services:
  mongodb:
    image: cr.yandex/crps5m51hmah43pmfb23/mongodb:4.4
    container_name: unic.chat.db.mongo
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    networks:
      - unicchat-backend
      - unicchat-frontend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

networks:
  unicchat-frontend:
    driver: bridge
    external: true
  unicchat-backend:
    driver: bridge
    external: true

volumes:
  mongodb_data:
    driver: local
