version: "3"
services:
  uc.media.score:
    image: cr.yandex/crpst6ndtaf70or2n2bb/solid.core/prod:demo250602
    container_name: unic.chat.solid
    restart: unless-stopped
    ports:
      - 8881:8080
      - 4443:443
    env_file:
      - ./solid.env
    networks:
      - unicchat-backend
networks:
  unicchat-backend:
    driver: bridge
    external: true


