version: "3"
services:
  unic.chat.appserver:
    container_name: unic.chat.appserver
    image: cr.yandex/crpvpl7g37r2id3i2qe5/unic_chat_appserver:prod.6-2.1.80-10
    restart: on-failure
    env_file:
      - appserver.env
    volumes:
      - chat_data:/app/uploads
    ports:
      - "8080:3000"
    environment:
      - VAULT__HOST=http://internal_IP:8200 # http://vault:80 если в одной сети  unic.chat.appserver  и vault
      - REDMINE_BOT_HOST=http://internal_IP:8201 # http://ucredminebot:8080 если в одной сети  unic.chat.appserver  и ucredminebot
    networks:
      - unicchat-frontend

networks:
  unicchat-frontend:
    driver: bridge
    external: true

volumes:
  chat_data:
    driver: local








