version: "3"
services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel debug
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - cache:/redis-data
volumes:
  cache:
    driver: local
