# unicomm medua server
# support@unicomm.pro
version: "3"
services:
  uc.media.server:
    image: unicommhub/unic.chat.media.server:1.1.2
    container_name: uc.media.server
    restart: unless-stopped
    network_mode: "host"
    command: --config /opt/media-server/server.yaml
    volumes:
      - ./config/server.yaml:/opt/media-server/server.yaml
