version: '3.8'

services:
  unicchat.documentserver:
    image: cr.yandex/crpst6ndtaf70or2n2bb/uniceditor:latest
    container_name: unicchat.documentserver
    depends_on:
      - unicchat.postgresql
      - unicchat.rabbitmq
    env_file:
      - ../env/documentserver_env.env
    ports:
      - '8880:80'
      - '8443:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    networks:
      - unicchat-network
    volumes:
      - documentserver_data:/var/www/uniceditor/Data
      - documentserver_log:/var/log/uniceditor
      - documentserver_cache:/var/lib/uniceditor/documentserver/App_Data/cache/files
      - documentserver_files:/var/www/uniceditor/documentserver-example/public/files
      - /usr/share/fonts

  unicchat.rabbitmq:
    container_name: unicchat.rabbitmq
    image: cr.yandex/crpst6ndtaf70or2n2bb/rabbitmq:latest
    restart: always
    networks:
      - unicchat-network
    expose:
      - '5672'

  unicchat.postgresql:
    container_name: unicchat.postgresql
    image: cr.yandex/crpst6ndtaf70or2n2bb/postgres:12
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    networks:
      - unicchat-network
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  documentserver_data:
    driver: local
  documentserver_log:
    driver: local
  documentserver_cache:
    driver: local
  documentserver_files:
    driver: local
  postgresql_data:
    driver: local

networks:
  unicchat-network:
    external: true
