version: '3.8'

services:
  unicchat.logger:
    image: cr.yandex/crpi5ll6mqcn793fvu9i/unic/uniclogger:prod
    container_name: unicchat.logger
    ports:
      - '8082:8080'
    networks:
      - unicchat-network
    restart: unless-stopped
    env_file:
      - ../logger.env
      - ../logger_creds.env

networks:
  unicchat-network:
    external: true
