version: '3.8'

services:
  unicchat-tasker:
    image: cr.yandex/crpi5ll6mqcn793fvu9i/unic/unicchatkbasetasker:prod
    container_name: unicchat-tasker
    restart: unless-stopped
    ports:
      - 8881:8080
    environment:
      - api.vault.url=http://unicchat-vault:80/
      - api.logger.url=http://unicchat-logger:8080/
    networks:
      - unicchat-network

networks:
  unicchat-network:
    external: true
