version: '3.8'

services:
  unicchat.vault:
    image: cr.yandex/crpi5ll6mqcn793fvu9i/unic/unicvault:prod
    container_name: unicchat.vault
    ports:
      - 8200:80
    volumes:
      - vault-data:/vault/file/
    environment:
      - api.logger.url=http://unicchat.logger:8080/
    env_file:
      - ../vault_creds.env
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    networks:
      - unicchat-network

volumes:
  vault-data:
    driver: local

networks:
  unicchat-network:
    external: true
