version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: unic.chat.minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_IP_OR_HOST=${MINIO_IP_OR_HOST}
    volumes:
      - minio_data:/data
    networks:
      - unicchat-backend
      - unicchat-frontend
    ports:
      - "9000:9000"
      - "9002:9001"
    command: server /data --console-address ":9001"
networks:
  unicchat-backend:
    external: true
  unicchat-frontend:
    external: true
volumes:
  minio_data:
    driver: local
